In [69]:
import numpy as np
from math import sqrt

In [70]:
def jacobi(A,b,x0,acc,it_max):                    
    t = 0                                        
    for i in range(0,len(A),1):                
        if 2*abs(A[i,i])>np.sum(abs(A[i])):
            t += 1
        else:
            break
    if t == len(A):
        x = np.zeros((2,len(A)),float)
        x[1,:] = x0
        k = 0
        while sqrt(sum((x[1]-x[0])**2))>acc and k<it_max:
            x[0,:] = x[1,:]
            for i in range(0,len(A),1):
                x[1,i] = (b[i]-(sum(A[i,:i]*x[0,:i])+sum(A[i,i+1:]*x[0,i+1:])))/A[i,i]
            k += 1
            return x[1]
    else:
        print("---Matrix is not correct!---")
        return x0,0,0

def jacobi_vec(A,b,x0,acc,it_max):
    t = 0
    for i in range(0,len(A),1):
        if 2*abs(A[i,i])>np.sum(abs(A[i])):
            t += 1
        else:
            break
            
    if t == len(A):
        
        L = np.zeros((len(A),len(A)),float)
        U = np.zeros((len(A),len(A)),float)
        D = np.zeros((len(A),len(A)),float)
        
        for i in range(0,len(A),1):
            L[i,:i] = A[i,:i]
            D[i,i] = A[i,i]    
            U[i,i+1:] = A[i,i+1:]
        x = np.zeros((2,len(A)),float)
        x[1,:] = x0
        k = 0
        
        while sqrt(sum((x[1]-x[0])**2))>acc and k<it_max:
            x[0,:] = x[1,:]
            x[1] = np.dot(np.linalg.inv(D),(np.dot(-(L+U),x[0])+b))
            k += 1
            return x[1]
    else:
        print("---Matrix is not correct!---")
        return x0,0,0

In [71]:
N = 3
alfa = 0.2
A = np.zeros((N,N),float)
b = np.zeros(N)
x0 = np.zeros(N)
A[0,0] = 2
A[0,1] = -1+alfa
A[N-1,N-1] = 2
A[N-1,N-2] = -1+alfa
b[0] = 1-alfa
b[N-1] = 1+alfa
x0[0] = 0.7
x0[N-1] = 0.8
for i in range(1,N-1,1):
    A[i,i]=2
    A[i,i+1]=-1+alfa
    A[i,i-1]=-1+alfa
    b[i]=0
    x0[i]=0.1*i
    
print(A)
print(b)

b = np.dot(A,x)
sol = jacobi(A, b, x0, 1/10000, 1000)
sol_v = jacobi_vec(A, b, x0, 1/10000, 1000)

[[ 2.  -0.8  0. ]
 [-0.8  2.  -0.8]
 [ 0.  -0.8  2. ]]
[0.8 0.  1.2]


In [72]:
x - sol

array([ 0.30747413, -0.14146139,  0.30747413])

In [73]:
x - sol_v

array([ 0.30747413, -0.14146139,  0.30747413])